// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVjDCg38fqU2B3X1QOiG3PRQnGZYgiKiw',
    appId: '1:455360450549:web:70f6aa57ce4b6265bcdabc',
    messagingSenderId: '455360450549',
    projectId: 'coindex-4870e',
    authDomain: 'coindex-4870e.firebaseapp.com',
    storageBucket: 'coindex-4870e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFKmzLi4BYMm06HH1sOb2JmbksgjUxJ60',
    appId: '1:455360450549:android:ad111caf6b0a2d64bcdabc',
    messagingSenderId: '455360450549',
    projectId: 'coindex-4870e',
    storageBucket: 'coindex-4870e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYZqjbf9aI-JYcuKgh65d9hqKPQkwsZ0A',
    appId: '1:455360450549:ios:4fd36f41f3b4683bbcdabc',
    messagingSenderId: '455360450549',
    projectId: 'coindex-4870e',
    storageBucket: 'coindex-4870e.appspot.com',
    iosBundleId: 'com.example.coindex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYZqjbf9aI-JYcuKgh65d9hqKPQkwsZ0A',
    appId: '1:455360450549:ios:4fd36f41f3b4683bbcdabc',
    messagingSenderId: '455360450549',
    projectId: 'coindex-4870e',
    storageBucket: 'coindex-4870e.appspot.com',
    iosBundleId: 'com.example.coindex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVjDCg38fqU2B3X1QOiG3PRQnGZYgiKiw',
    appId: '1:455360450549:web:2b7ff3a2a7221f10bcdabc',
    messagingSenderId: '455360450549',
    projectId: 'coindex-4870e',
    authDomain: 'coindex-4870e.firebaseapp.com',
    storageBucket: 'coindex-4870e.appspot.com',
  );
}
